### ISSUE TITLE
Uncaught TypeError: file.read(...).then(...).fail is not a function

### ISSUE THREAD

**Issue by dschnee** [Ge-Bra/unsaved-changes#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0-beta1
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [unsaved-changes](https://github.com/Ge-Bra/unsaved-changes) package, v0.1.0
### Stack Trace

Uncaught TypeError: file.read(...).then(...).fail is not a function

```
At /C:/Users/David/.atom/packages/unsaved-changes/lib/unsaved-changes.coffee:54

TypeError: file.read(...).then(...).fail is not a function
  at Object.module.exports.UnsavedChanges.show (C:\Users\David\.atom\packages\unsaved-changes\lib\unsaved-changes.coffee:56:12)
  at atom-workspace.subscriptions.add.atom.commands.add.unsaved-changes:show (C:\Users\David\.atom\packages\unsaved-changes\lib\unsaved-changes.coffee:17:35)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\command-registry.js:243:29)
  at C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\David\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\window-event-handler.js:97:20)

```
### Commands

```
  2x -7:46.8.0 settings-view:open (atom-text-editor.editor)
  3x -6:33.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:33.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:10.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:10.5.0 find-and-replace:select-undo (atom-text-editor.editor.is-focused)
     -0:02.7.0 unsaved-changes:show (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "webbox-color",
      "wrap-guide",
      "vim-mode",
      "multi-wrap-guide",
      "project-manager",
      "merge-conflicts",
      "tree-view-breadcrumb",
      "symbols-tree-view",
      "fancy-bracket-matcher",
      "letter-spacing",
      "apex-superfish-menu",
      "autohide-tree-view",
      "documentation-renderer",
      "terminal-plus",
      "terminal-status",
      "seti-icons"
    ],
    "openEmptyEditorOnStart": false,
    "excludeVcsIgnoredPaths": false,
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "earthsung-by-jackson-syntax"
    ],
    "packagesWithKeymapsDisabled": []
  }
}
```
### Installed Packages

``` coffee
# User
atom-commander, v0.4.2
color-picker, v2.0.13
copy-filename, v1.0.1
earthsung-by-jackson-syntax, v0.3.0
file-icon-supplement, v0.8.3
file-icons, v1.6.11
fonts, v0.7.0
goto-mathematica, v0.1.0
hex, v0.6.2
language-mathematica, v0.1.0
linter, v1.9.1
linter-chktex, v1.2.0
linter-gcc, v0.3.8
linter-js-standard, v3.2.1
linter-matlab, v1.0.0
linter-tidy, v1.0.1
menu-manager, v0.4.3
minimap, v4.15.0
minimap-find-and-replace, v4.3.1
minimap-hide, v0.3.0
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
neon-cursor, v0.2.0
pdf-view, v0.34.0
pigments, v0.18.1
project-view, v0.1.2
Sublime-Style-Column-Selection, v1.3.0
sync-settings, v0.6.0
tabs-to-spaces, v0.11.1
tool-bar, v0.1.9
toolbar-iconshortcuts, v1.0.0
trailing-spaces, v0.3.2
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.2
unsaved-changes, v0.1.0
useful-context-menu, v0.3.0

# Dev
No dev packages
```

**Comment by p0la** [comment]
Same error here

**Comment by nonameolsson** [comment]
Same here!

**Comment by AWTrost** [comment]
:+1:

**Comment by crankyOldCanuck** [comment]
No longer use Atom, no longer supporting this. Sorry.

**Comment by p0la** [comment]
Thx for the feed back. Can I ask what you are using instead ? Sublime ?

**Comment by potnik** [comment]
Changing line 56 in my Unsaved-Changes.coffee file from .fail to .catch fixed this for me.

**Comment by merlyn333** [comment]
Same error here

**Comment by gertsonderby** [comment]
Given the lack of support from original author, is there a fork that can take over, maybe transfer the package or something?

**Comment by fonfonx** [comment]
I forked the repo on my github account and I corrected the bug. You can download the new version of the package whose name is now `atom-unsaved-changes`. It is available [here](https://atom.io/packages/atom-unsaved-changes).
